export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

export const LOAD_VENUES_SUCCESS = 'LOAD_VENUES_SUCCESS';
export const SORT_VENUES_DATA = 'SORT_VENUES_DATA';
export const FILTER_VENUES_DATA = 'FILTER_VENUES_DATA';

export const LOAD_AMENITIES_SUCCESS = 'LOAD_AMENITIES_SUCCESS';
export const SORT_AMENITIES_DATA = 'SORT_AMENITIES_DATA';
export const FILTER_AMENITIES_DATA = 'FILTER_AMENITIES_DATA';
export const FILTER_AMENITIES_BYTYPE_DATA = 'FILTER_AMENITIES_BYTYPE_DATA';
export const AMENITIES_VENUE_LOAD_SUCCESS = 'AMENITIES_VENUE_LOAD_SUCCESS';

export const LOAD_POI_SUCCESS = 'LOAD_POI_SUCCESS';
export const FILTER_POI_DATA = 'FILTER_POI_DATA';
export const SORT_POI_DATA = 'SORT_POI_DATA';
export const POI_VENUE_LOAD_SUCCESS = 'POI_VENUE_LOAD_SUCCESS';

export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';

export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const SORT_POSTS_DATA = 'SORT_POSTS_DATA';
export const FILTER_POSTS_DATA = 'FILTER_POSTS_DATA';
export const ADDPOST_VENUE_LOAD = 'ADDPOST_VENUE_LOAD';


export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT_SUCCESS';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_FAVORITES_SUCCESS = 'LOAD_FAVORITES_SUCCESS';
export const LOAD_SCORES_SUCCESS = 'LOAD_SCORES_SUCCESS';
